### ISSUE TITLE
两个脚本均已失效

### ISSUE THREAD

**Issue by T5eng** [Nanyan89757/-#2]
京东脚本运行提示“点太快了，下次再来”

淘宝活动链接有误 https://market.m.taobao.com/app/tb-source-app/campaign/pages/index

**Comment by gongchensu** [comment]
附议啊，是本人写的吗？希望作者大大更新

**Comment by Nanyan89757** [comment]
淘宝的失效了 淘宝效率太高已经开始判断是否为h5页面 京东这边显示还可以

**Comment by T5eng** [comment]
在win+chorme重新测试了jd的确实可以。在mac+safari上还是显示操作太快的。
